baseurl = "http://www.nathanss.com"
title = "Nathan S. Schneider"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[markup.goldmark.renderer]
    unsafe = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Nathan S. Schneider"
  info = "Senior Software Engineer"
  description = "10+ years of experience with a strong passion for collaboration and knowledge sharing."
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2015

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/nathanss/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/nsschneider/"

# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"