title = "Nathan S. Schneider"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true
defaultContentLanguageFallback = true

[languages]
  [languages.en]
    weight = 1
    languageName = "Change to English 🇺🇸"
  [languages.pt-BR]
    weight = 2
    languageName = "Trocar para português :brazil:"

[markup.goldmark.renderer]
    unsafe = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true


[pagination]
pagerSize = 20

[services]
[services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[languages.en.params]
  info = "Senior Software Engineer"
  description = "10+ years of experience with a strong passion for collaboration and knowledge sharing."
  description2 = "Loves music and video-games."
  keywords = "blog,developer,personal"

[languages.pt-BR.params]
  info = "Senior Software Engineer"
  description = "Mais de 10 anos de experiência. Colaborativo e adora compartilhar conhecimento."
  description2 = "Ama música e video-games."
  keywords = "blog,developer,personal"

[params]
  author = "Nathan S. Schneider"  
  avatarurl = "images/avatar.jpg"
  faviconSVG = "/images/favicon.svg"
  since = 2015
  enableTwemoji = true
  colorScheme = "dark"
  hidecolorschemetoggle = false

customSCSS = ["scss/custom.scss"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/nathanss/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/nsschneider/"

# Menu links
[[languages.en.menu.main]]
  name = "Blog"
  weight = 4
  url  = "posts/"
[[languages.en.menu.main]]
  name = "About me"
  weight = 2
  url = "about/"
[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.pt-BR.menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"